### ISSUE TITLE
Fix CircleCI passing despite failed tests

### ISSUE THREAD

**Issue by jcruz** [cs121-team-panda/coconut-interpreter-flask#47] opened 2018-03-01 00:00 UTC
See [here](https://circleci.com/gh/cs121-team-panda/coconut-interpreter-flask/24?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)

**Comment by mjenrungrot** [comment] 2018-03-01 03:44
Closed via #46. The tests are passed.

**Comment by jcruz** [comment] 2018-03-11 23:37
@mjenrungrot Please see https://github.com/cs121-team-panda/coconut-interpreter-flask/commit/10891082fbdda1bcb16dc6defc6ac675a7529d0b.

References:
- CircleCI page showing failure in test summary but result is successful build: https://circleci.com/gh/cs121-team-panda/coconut-interpreter-flask/40
- Branch: https://github.com/cs121-team-panda/coconut-interpreter-flask/tree/ci-is-broken

**Comment by mjenrungrot** [comment] 2018-03-19 01:32
@jcruz It's probably the errors are suppressed. See ref for the fix.

Ref:
- https://support.circleci.com/hc/en-us/articles/115015733328-Tests-fail-but-job-finishes-successfully

**Comment by mjenrungrot** [comment] 2018-03-20 22:55
Fixed in #60

**Comment by jcruz** [comment] 2018-03-20 23:08
Needs further testing

**Comment by mjenrungrot** [comment] 2018-03-21 04:30
The issue is from the fact that running `python manage.py test` does not give exit code 1.

**Comment by mjenrungrot** [comment] 2018-03-21 04:44
See PR #63

**Closed** 2018-03-21 07:26 UTC
Labels: bug
